### PR TITLE
Added classification results

### PR DESCRIPTION
**Pull request by Zitong-Chen-16**
Added scratch codes for classification for issue #12

### CODE REVIEW

**Comment by shntnu** [comment]
@Zitong-Chen-16 This looks great!

Quick Q:  Where did you get the `0.load_parquet_files.ipynb` logic from? The joins can be complicated so I'm just make sure you've got the logic from some standard reference (like pycytominer

**Review by shntnu — COMMENTED** [review]
Minor fix: we might as well change "wt" to "reference" so we needn't revisit this later

**Comment by Zitong-Chen-16** [comment]
> Quick Q: Where did you get the logic for joins in `0.load_parquet_files.ipynb`? The joins can be complicated (because of the way CellProfiler defines relationships), so I'm just making sure you've got the logic from some standard reference (like pycytominer)

I got the logic from the merge_single_cell function in pycytominer! I tried using pycytominer directly but had some issues so didn't end up using it.

**Comment by shntnu** [comment]
> I got the logic from the merge_single_cell function in pycytominer! I tried using pycytominer directly but had some issues so didn't end up using it.

Perfect! 

Feel free to leave this PR open until we've come to some reasonable conclusion in #12

**Review by shntnu — APPROVED** [review]
I skimmed it but didn't look deeply. Please proceed with merging

**Pull request merged**
